name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:  
  Test:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make install-dev

      - name: Lint
        run: make lint

      - name: Test
        run: make coverage
